In [68]:
"""1. Create a function that transposes a 2D matrix."""

import numpy
def transpose_matrix(l):
    print(numpy.array(l).transpose())
    
transpose_matrix([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
transpose_matrix([[5, 5],[6, 7],[9, 1]])

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[5 6 9]
 [5 7 1]]


In [61]:
"""2. Create a function that determines whether a string is a valid hex code.
A hex code must begin with a pound key # and is exactly 6 characters in
length. Each character must be a digit from 0-9 or an alphabetic character
from A-F. All alphabetic characters may be uppercase or lowercase."""

def is_valid_hex_code(s):
    n= True
    for i in s:
        if i.lower() not in '#abcdef0123456789' or len(s) != 7:
            n= False
    print(n)
    
is_valid_hex_code("#CD5C5C")
is_valid_hex_code("#EAECEE")
is_valid_hex_code("#eaecee")
is_valid_hex_code("#CD5C58C")
is_valid_hex_code("#CD5C5Z")
is_valid_hex_code("#CD5C&C")
is_valid_hex_code("CD5C5C")

True
True
True
False
False
False
False


In [49]:
"""3. Given a list of math equations (given as strings), return the percentage of
correct answers as a string. Round to the nearest whole number."""

import re,math
def mark_maths(l):
    l1=[]
    for i in l:
        s=re.findall("([0-9+-]+)=",i)[0]
        if eval(s)==int(re.findall("=([-0-9]+)",i)[0]):
            l1.append(1)
    print(f'{math.ceil((sum(l1)/len(l))*100)}%')
    
mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"])
mark_maths(["1-2=-2"])
mark_maths(["2+3=5", "4+4=9", "3-1=2"])

75%
0%
67%


In [29]:
"""4. There are two players, Alice and Bob, each with a 3-by-3 grid. A referee
tells Alice to fill out one particular row in the grid (say the second row) by
putting either a 1 or a 0 in each box, such that the sum of the numbers in that
row is odd. The referee tells Bob to fill out one column in the grid (say the first
column) by putting either a 1 or a 0 in each box, such that the sum of the
numbers in that column is even.
Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give
an even sum, and (most important) they’ve each written down the same
number in the one square where their row and column intersect."""

def magic_square_game(l1,l2):
    n=False
    if l2[1][l1[0]-1] == l1[1][l2[0]-1]:
        n=True
    print(n)

magic_square_game([2, "100"], [1, "101"])
magic_square_game([2, "001"], [1, "101"]) 
magic_square_game([3, "111"], [2, "011"]) 
magic_square_game([1, "010"], [3, "101"]) 

False
True
True
False


In [28]:
"""5. From point A, an object is moving towards point B at constant velocity va
(in km/hr). From point B, another object is moving towards point A at constant
velocity vb (in km/hr). Knowing this and the distance between point A and B
(in km), write a function that returns how much time passes until both objects
meet.
Format the output like this:
2h 23min 34s"""

def lets_meet(dist,va,vb):
    time=dist/(va+vb)
    hr =int(time)
    mint=int((time-hr)*60)
    sec=int((((time-hr)*60)-mint)*60)
    print(f'{hr}h {mint}min {sec}s')
    
lets_meet(100, 10, 30)
lets_meet(280, 70, 80)
lets_meet(90, 75, 65)

2h 30min 0s
1h 52min 0s
0h 38min 34s
