In [12]:
"""1. Create a function based on the input and output. Look at the examples, there is a pattern."""
def secret(s):
    s=s.replace(".", " ")
    print(f'<{s[0]} class=\"{s[2:]}\"></p>')
    
secret("p.one.two.three")
secret("p.one")
secret("p.four.five")

<p class="one two three"></p>
<p class="one"></p>
<p class="four five"></p>


In [15]:
"""2. Create a function which counts how many lone 1s appear in a given number. Lone means the number doesn't appear twice 
or more in a row."""
import re
def count_lone_ones(n):
    result=re.findall("((?<!1)1(?!1))",str(n))
    print(len(result))
    
count_lone_ones(101)
count_lone_ones(1191)
count_lone_ones(1111)
count_lone_ones(462)


2
1
0
0


In [32]:
"""3. Write a method that accepts two integer parameters rows and cols. The output is a 2d array of numbers displayed in 
column-major order, meaning the numbers shown increase sequentially down each column and wrap to the top of the next column
to the right once the bottom of the current column is reached."""

import numpy as np
def printGrid(n,m):
    x=np.arange(1,(n*m)+1).reshape(n,m)
    print(x)
    
printGrid(3, 6)
printGrid(5, 3)  
printGrid(4, 1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1]
 [2]
 [3]
 [4]]


In [28]:
"""4. Given a list of integers, return the smallest positive integer not present in the list.
Here is a representative example.
Consider the list: [-2, 6, 4, 5, 7, -1, 7, 1, 3, 6, 6, -2, 9, 10, 2, 2]
After reordering, the list becomes: [-2, -2, -1, 1, 2, 2, 3, 4, 5, 6, 6, 6, 7, 7, 9, 10]
from which we see that the smallest missing positive integer is 8."""

def min_miss_pos(l):
    l=sorted(l)
    l1=[]
    for i in range(1,(max(l))):
        if i in l:
            pass
        else:
            l1.append(i)
    print(l1[0])
    
min_miss_pos([-2, 6, 4, 5, 7, -1, 1, 3, 6, -2, 9, 10, 2, 2])
min_miss_pos([5, 9, -2, 0, 1, 3, 9, 3, 8, 9])
min_miss_pos([0, 4, 4, -1, 9, 4, 5, 2, 10, 7, 6, 3, 10, 9])

8
2
1


In [19]:
"""5. Google is launching a network of autonomous pizza delivery drones and
wants you to create a flexible rewards system (Pizza Points™) that can be
tweaked in the future. The rules are simple: if a customer has made at least N
orders of at least Y price, they get a FREE pizza!
Create a function that takes a dictionary of customers, a minimum number of
orders and a minimum order price. Return a list of customers that are eligible
for a free pizza."""

def pizza_points(in_dict,min_order,min_price):
    output = []
    for customer in in_dict.keys():
        if len([order_price for order_price in in_dict[customer] if order_price > min_price]) > min_order:
            output.append(customer)
    print(output)

customers = {
  "Batman": [22, 30, 11, 17, 15, 52, 27, 12],
  "Spider-Man": [5, 17, 30, 33, 40, 22, 26, 10, 11, 45]
}
    
pizza_points(customers, 5, 20)
pizza_points(customers, 3, 10)
pizza_points(customers, 5, 100)

['Spider-Man']
['Batman', 'Spider-Man']
[]
